domain: joan0fsnark.com       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: http://www.joan0fsnark.com
# baseurl: /friendly-it/
# url: https://my-site.github.io  # the base hostname and protocol for your site, e.g. http://example.com

# Site settings
title: Friendly IT Services
email: alenad@gmail.com
description: "Here to solve your tech woes!"


# Team names, titles and social links
people:
- name: Alena Davis
  pic: alena
  position: Software Engineer/Tech Guru
  social:
    - title: twitter
      url: https://twitter.com/joan0fsnark
    - title: github
      url: https://github.com/joan0fsnark
    - title: linkedin
      url: https://www.linkedin.com/in/alenajd/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
  # - title: twitter
    # url: http://twitter.com/jekyllrb
  # - title: facebook
    # url:
  # - title: stack-overflow
    # url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
    # url: http://bitbucket.org/jekyll
  # - title: github
    # url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
remote_theme: y7kim/agency-jekyll-theme
